"""Add image uri filed to invoice
Revises: d694be390dec
Create Date: 2022-03-14 03:51:14.170129

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "fd849f2a56de"
down_revision = "d694be390dec"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("invoices", sa.Column("image_uri", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("invoices", "image_uri")
    # ### end Alembic commands ###
