"""empty message

Revision ID: d694be390dec
Revises: 9d261f4ad8a2
Create Date: 2022-03-14 03:19:44.620726

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "d694be390dec"
down_revision = "9d261f4ad8a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("name", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "name")
    # ### end Alembic commands ###
