"""Added role to user model

Revision ID: fa39752f503d
Revises: e5ea629c35a5
Create Date: 2022-04-10 20:20:13.006135

"""
import sqlalchemy as sa
import ulid
from sqlalchemy import Column, DateTime, ForeignKey, String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship
from sqlalchemy.orm.session import Session
from sqlalchemy.sql import func

from alembic import op
from app.db.session import Base

# revision identifiers, used by Alembic.
revision = "fa39752f503d"
down_revision = "e5ea629c35a5"
branch_labels = None
depends_on = None


Base = declarative_base()


class User(Base):
    __tablename__ = "users"

    id = Column(String, default=ulid.ulid, primary_key=True)

    name = Column(String, nullable=True)
    role = Column(String, nullable=True)
    paid_plan = Column(String, nullable=True)
    stripe_session_id = Column(String, nullable=True)
    email = Column(String, nullable=False, unique=True)
    password_hash = Column(String, nullable=False)

    created_on = Column(DateTime, server_default=func.now())
    updated_on = Column(DateTime, onupdate=func.now())


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("role", sa.String(), nullable=True))
    # ### end Alembic commands ###

    # Add hard coded admin user
    db = Session(bind=op.get_bind())

    admin_user = User(
        name="Easy Invoice Management Admin",
        password_hash="$2b$12$0C1R8FnE3MORSqQUHP9EJucIgQwBn8IOYUPfEeZCgptLiVkvQ2M.e",
        email="admin@easyinvoicemanager.com",
        role="admin",
    )
    db.add(admin_user)
    db.commit()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###
