"""Add user and organization id to vendor

Revision ID: 59a76a405fce
Revises: d1e622aadfb6
Create Date: 2022-03-27 02:34:12.300107

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "59a76a405fce"
down_revision = "d1e622aadfb6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("vendors", sa.Column("user_id", sa.String(), nullable=True))
    op.add_column("vendors", sa.Column("organization_id", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_vendors_organization_id"), "vendors", ["organization_id"], unique=False
    )
    op.create_index(op.f("ix_vendors_user_id"), "vendors", ["user_id"], unique=False)
    op.create_foreign_key(None, "vendors", "users", ["user_id"], ["id"])
    op.create_foreign_key(None, "vendors", "organizations", ["organization_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "vendors", type_="foreignkey")
    op.drop_constraint(None, "vendors", type_="foreignkey")
    op.drop_index(op.f("ix_vendors_user_id"), table_name="vendors")
    op.drop_index(op.f("ix_vendors_organization_id"), table_name="vendors")
    op.drop_column("vendors", "organization_id")
    op.drop_column("vendors", "user_id")
    # ### end Alembic commands ###
