"""Add dates to CategoryInvoiceAssociation and add AgeingReport table

Revision ID: e5ea629c35a5
Revises: 59a76a405fce
Create Date: 2022-04-03 23:37:31.374551

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e5ea629c35a5"
down_revision = "59a76a405fce"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ageing_reports",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("user_id", sa.String(), nullable=True),
        sa.Column("organization_id", sa.String(), nullable=True),
        sa.Column("csv_uri", sa.String(), nullable=True),
        sa.Column(
            "created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("updated_on", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ageing_reports_organization_id"),
        "ageing_reports",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ageing_reports_user_id"), "ageing_reports", ["user_id"], unique=False
    )
    op.add_column(
        "category_invoice_associations",
        sa.Column(
            "created_on", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
    )
    op.add_column(
        "category_invoice_associations",
        sa.Column("updated_on", sa.DateTime(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("category_invoice_associations", "updated_on")
    op.drop_column("category_invoice_associations", "created_on")
    op.drop_index(op.f("ix_ageing_reports_user_id"), table_name="ageing_reports")
    op.drop_index(
        op.f("ix_ageing_reports_organization_id"), table_name="ageing_reports"
    )
    op.drop_table("ageing_reports")
    # ### end Alembic commands ###
