"""added leads db

Revision ID: 21b14e7531e8
Revises: 470275672a87
Create Date: 2022-11-08 11:09:42.208238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21b14e7531e8'
down_revision = '470275672a87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leads',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('meta', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('edit', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['company'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leads')
    # ### end Alembic commands ###
