"""added reject and approved fields in Invoice table

Revision ID: 470275672a87
Revises: 1ec87e1cc1b7
Create Date: 2022-11-01 12:08:32.650714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '470275672a87'
down_revision = '1ec87e1cc1b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('is_rejected', sa.Boolean(), nullable=True))
    op.add_column('invoices', sa.Column('is_approved', sa.Boolean(), nullable=True))
    op.add_column('invoices', sa.Column('rejection_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'rejection_reason')
    op.drop_column('invoices', 'is_approved')
    op.drop_column('invoices', 'is_rejected')
    # ### end Alembic commands ###
