"""removed unique true from category name

Revision ID: 47a074fc91b8
Revises: 3e2fc1555c35
Create Date: 2022-12-21 08:51:31.620555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47a074fc91b8'
down_revision = '3e2fc1555c35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('categories_name_key', 'categories', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('categories_name_key', 'categories', ['name'])
    # ### end Alembic commands ###
