"""add payment_details model

Revision ID: 54851f4cbe99
Revises: e4cc6b94f14a
Create Date: 2022-09-01 12:25:22.734297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54851f4cbe99'
down_revision = 'e4cc6b94f14a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_details',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('invoice_number', sa.String(), nullable=True),
    sa.Column('account', sa.String(), nullable=True),
    sa.Column('amount', sa.DECIMAL(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment_details')
    # ### end Alembic commands ###
