"""added organization and lead relationship

Revision ID: 92f0493ec336
Revises: da75fca02135
Create Date: 2022-11-14 15:47:25.265967

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '92f0493ec336'
down_revision = 'da75fca02135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('create_date', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('company', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('meta', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('source', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('reference', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('edit', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['company'], ['organizations.id'], name='lead_company_fkey'),
    sa.PrimaryKeyConstraint('id', name='lead_pkey')
    )
    # ### end Alembic commands ###
