"""added invoice_id field in RequestedApprovers

Revision ID: c3e361c91c8d
Revises: 92f0493ec336
Create Date: 2022-11-21 08:28:13.028709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3e361c91c8d'
down_revision = '92f0493ec336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requested_approvers', sa.Column('invoice_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('requested_approvers', 'invoice_id')
    # ### end Alembic commands ###
