"""added leads db

Revision ID: da75fca02135
Revises: 21b14e7531e8
Create Date: 2022-11-08 07:19:51.237584

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da75fca02135'
down_revision = '21b14e7531e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lead',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('company', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('meta', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('reference', sa.String(), nullable=True),
    sa.Column('edit', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['company'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lead')
    # ### end Alembic commands ###
