"""empty message

Revision ID: e679b059e655
Revises: fa39752f503d
Create Date: 2022-05-20 16:53:42.566562

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e679b059e655"
down_revision = "fa39752f503d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invoices", sa.Column("image_content_type", sa.String(), nullable=True)
    )
    op.alter_column("invoices", "image_uri", new_column_name="image_path")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "invoices",
        sa.Column("image_uri", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("invoices", "image_content_type")
    op.alter_column("invoices", "image_path", new_column_name="image_uri")
    # ### end Alembic commands ###
