"""added multiple columns in Vendor model

Revision ID: ef0c2e70b1e4
Revises: a65127cc0d90
Create Date: 2023-12-05 09:26:42.341948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef0c2e70b1e4'
down_revision = 'a65127cc0d90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendors', sa.Column('vendor_number', sa.Integer(), nullable=True))
    op.add_column('vendors', sa.Column('external_vendor_id', sa.Integer(), nullable=True))
    op.add_column('vendors', sa.Column('address_one', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('address_two', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('city', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('state', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('pincode', sa.Integer(), nullable=True))
    op.add_column('vendors', sa.Column('attention', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('fax', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('parent_vendor', sa.Integer(), nullable=True))
    op.add_column('vendors', sa.Column('account', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('tax_id', sa.String(), nullable=True))
    op.add_column('vendors', sa.Column('note', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'vendors', ['parent_vendor'])
    op.create_unique_constraint(None, 'vendors', ['phone'])
    op.create_unique_constraint(None, 'vendors', ['external_vendor_id'])
    op.create_unique_constraint(None, 'vendors', ['vendor_number'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'note')
    op.drop_column('vendors', 'tax_id')
    op.drop_column('vendors', 'account')
    op.drop_column('vendors', 'parent_vendor')
    op.drop_column('vendors', 'fax')
    op.drop_column('vendors', 'phone')
    op.drop_column('vendors', 'attention')
    op.drop_column('vendors', 'pincode')
    op.drop_column('vendors', 'state')
    op.drop_column('vendors', 'city')
    op.drop_column('vendors', 'address_two')
    op.drop_column('vendors', 'address_one')
    op.drop_column('vendors', 'external_vendor_id')
    op.drop_column('vendors', 'vendor_number')
    # ### end Alembic commands ###
